export const mockDossiers = [
  {
    id: "DOS-001",
    numero: "PRX-2024-001",
    source: "PRAXEDO" as const,
    statut: "FACTURABLE" as const,
    agence: "Agence Paris",
    technicien: "Jean Dupont",
    montant: 1250.5,
    dateCreation: "2024-10-15",
    dateModification: "2024-10-20",
    reglesAppliquees: ["REGLE-001", "REGLE-003"],
    notes: "Intervention standard",
  },
  {
    id: "DOS-002",
    numero: "PID-2024-002",
    source: "PIDI" as const,
    statut: "NON_FACTURABLE" as const,
    agence: "Agence Lyon",
    technicien: "Marie Martin",
    montant: 0,
    dateCreation: "2024-10-16",
    dateModification: "2024-10-18",
    reglesAppliquees: ["REGLE-002"],
    notes: "Intervention gratuite - garantie",
  },
  {
    id: "DOS-003",
    numero: "PRX-2024-003",
    source: "PRAXEDO" as const,
    statut: "CONDITIONNEL" as const,
    agence: "Agence Marseille",
    technicien: "Pierre Bernard",
    montant: 850.0,
    dateCreation: "2024-10-17",
    dateModification: "2024-10-19",
    reglesAppliquees: ["REGLE-001", "REGLE-004"],
    notes: "En attente de validation client",
  },
  {
    id: "DOS-004",
    numero: "PID-2024-004",
    source: "PIDI" as const,
    statut: "FACTURABLE" as const,
    agence: "Agence Toulouse",
    technicien: "Sophie Laurent",
    montant: 2100.75,
    dateCreation: "2024-10-18",
    dateModification: "2024-10-20",
    reglesAppliquees: ["REGLE-001", "REGLE-003", "REGLE-005"],
    notes: "Intervention complète",
  },
  {
    id: "DOS-005",
    numero: "PRX-2024-005",
    source: "PRAXEDO" as const,
    statut: "FACTURABLE" as const,
    agence: "Agence Bordeaux",
    technicien: "Luc Moreau",
    montant: 1500.0,
    dateCreation: "2024-10-19",
    dateModification: "2024-10-20",
    reglesAppliquees: ["REGLE-001"],
    notes: "Intervention standard",
  },
]

export const mockRegles = [
  {
    id: "REGLE-001",
    nom: "Facturation Standard",
    description: "Règle de facturation standard pour les interventions",
    condition: "montant > 0 AND statut != 'GRATUIT'",
    action: "FACTURER",
    actif: true,
    priorite: 1,
  },
  {
    id: "REGLE-002",
    nom: "Interventions Garantie",
    description: "Pas de facturation pour les interventions sous garantie",
    condition: "type_intervention == 'GARANTIE'",
    action: "NE_PAS_FACTURER",
    actif: true,
    priorite: 2,
  },
  {
    id: "REGLE-003",
    nom: "Surcharge Orange",
    description: "Surcharge de 10% pour les clients Orange",
    condition: "client == 'ORANGE'",
    action: "APPLIQUER_SURCHARGE_10",
    actif: true,
    priorite: 3,
  },
  {
    id: "REGLE-004",
    nom: "Validation Requise",
    description: "Nécessite validation avant facturation",
    condition: "montant > 5000",
    action: "ATTENDRE_VALIDATION",
    actif: true,
    priorite: 4,
  },
  {
    id: "REGLE-005",
    nom: "Déplacement Inclus",
    description: "Frais de déplacement inclus dans le montant",
    condition: "distance > 50",
    action: "INCLURE_DEPLACEMENT",
    actif: false,
    priorite: 5,
  },
]

export const mockAuditLogs = [
  {
    id: "LOG-001",
    action: "CREATION",
    entite: "DOSSIER",
    entiteId: "DOS-001",
    utilisateur: "admin@kyntus.fr",
    timestamp: "2024-10-15T10:30:00Z",
    details: "Création du dossier PRX-2024-001",
    ancien: null,
    nouveau: { statut: "FACTURABLE" },
  },
  {
    id: "LOG-002",
    action: "MODIFICATION",
    entite: "DOSSIER",
    entiteId: "DOS-002",
    utilisateur: "user@kyntus.fr",
    timestamp: "2024-10-16T14:15:00Z",
    details: "Changement de statut",
    ancien: { statut: "CONDITIONNEL" },
    nouveau: { statut: "NON_FACTURABLE" },
  },
  {
    id: "LOG-003",
    action: "CREATION",
    entite: "REGLE",
    entiteId: "REGLE-001",
    utilisateur: "admin@kyntus.fr",
    timestamp: "2024-10-01T09:00:00Z",
    details: "Création de la règle de facturation standard",
    ancien: null,
    nouveau: { nom: "Facturation Standard", actif: true },
  },
]
